language: haskell
sudo: false
cache:
  directories:
    - $HOME/.cabal
    - $HOME/.ghc
branches:
  only:
    - master
before_install:
  - cabal install 'happy >= 1.19.4'
  - cabal install 'alex >= 3.1.3'
#deploy:
#  provider: heroku
#  api_key:
#    secure: hBbPLNburzk/YY3hbpgdmbMdfk/osgh76fYBui1Yx6CYBTfMRUii22y8rtrCeu2BD6bEVEoSzFEelxg/LsVUjHIBnowXkl26lu3qbt6WpXi6KIyNJx/Y0U1gyoghW5hHqf2OL0u4zdHc7/jueVNmPcIDqq7XHUq84xi6TvAHwJY=
#  app: lambdacircus
#  on:
#    repo: mithrandi/lambdacircus
#  skip_cleanup: true
#  strategy: git
notifications:
  email: false
