language: haskell
before_install:
  - npm install coffee-script -g
  - cabal install 'alex >= 3.0.5'
script:
  - cabal configure && cabal build
before_deploy:
  - coffee -cb templates/default-layout.coffee
  - git config user.name 'Travis Builder'
  - git config user.email 'travis@mithrandi.net'
  - git rm templates/default-layout.coffee
  - git add -f templates/default-layout.js static/
  - git commit -m 'Add built static assets.'
deploy:
  provider: heroku
  api_key:
    secure: hBbPLNburzk/YY3hbpgdmbMdfk/osgh76fYBui1Yx6CYBTfMRUii22y8rtrCeu2BD6bEVEoSzFEelxg/LsVUjHIBnowXkl26lu3qbt6WpXi6KIyNJx/Y0U1gyoghW5hHqf2OL0u4zdHc7/jueVNmPcIDqq7XHUq84xi6TvAHwJY=
  app: lambdacircus
  on:
    repo: mithrandi/lambdacircus
  skip_cleanup: true
  strategy: git
