Default: &defaults
  host: "*4"
  port: 3000
  copyright: Insert copyright statement here
  #analytics: UA-YOURCODE

Development:
  approot: "https://localhost:3443"
  <<: *defaults

Testing:
  <<: *defaults

Staging:
  <<: *defaults

Production:
  approot: "https://qdb.codehash.net"
  <<: *defaults
