Default: &defaults
  host: "*4"
  port: 3000
  copyright: Insert copyright statement here
  #analytics: UA-YOURCODE

Development:
  approot: "http://localhost:3000"
  <<: *defaults

Testing:
  <<: *defaults

Staging:
  <<: *defaults

Production:
  approot: "http://qdb.codehash.net"
  <<: *defaults
