Default: &defaults
  database: FlyingCircus.sqlite3
  poolsize: 10

Development:
  <<: *defaults

Test:
  database: FlyingCircus_test.sqlite3
  <<: *defaults

Staging:
  database: FlyingCircus_staging.sqlite3
  poolsize: 100
  <<: *defaults

Production:
  database: FlyingCircus_production.sqlite3
  poolsize: 100
  <<: *defaults
